server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /hesap-silme {
        try_files /hesap-silme.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
